### ISSUE TITLE
Tests failed

### ISSUE THREAD

**Issue by rojasTob** [TwilioDevEd/sample-template-django#4]
I tried to execute the tests, but I got the following:

```
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 83
```
Could you check this? Or maybe mention it in the Readme file?

**Comment by mrcrow85** [comment]
@rojasTob Can you check if you have the latest chrome version installed?

**Comment by rojasTob** [comment]
@mrcrow85 yes, I do not have the 83 version, but I think it would be good to mention this in the Readme. What do you think?

**Comment by mrcrow85** [comment]
Ok I will. I just wanted to be sure you didn't get this error with the latest chrome version 🙂

**Comment by rojasTob** [comment]
@mrcrow85 awesome! Thank you! :)
